/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_fu_server_ServerLib */

#ifndef _Included_com_fu_server_ServerLib
#define _Included_com_fu_server_ServerLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fu_server_ServerLib
 * Method:    starpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_starpServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    closeServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_closeServer
  (JNIEnv *, jobject);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    sendData
 * Signature: (I[B)J
 */
JNIEXPORT jlong JNICALL Java_com_fu_server_ServerLib_sendData
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    sendCmd
 * Signature: (IB)J
 */
JNIEXPORT jlong JNICALL Java_com_fu_server_ServerLib_sendCmd
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    closeClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_closeClient
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fu_server_ServerLib
 * Method:    refreshFds
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_fu_server_ServerLib_refreshFds
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
